### ISSUE TITLE
Webpage cannot be found for Appsody Java extension project

### ISSUE THREAD

**Issue by eharris369** [kabanero-io/appsodyExtension#1]
I created an Appsody Java extension project in Codewind for Eclipse running on Windows 10.  It starts fine but when I try to open the application the browser shows a webpage not found error.  Looking at the container, the port looks correct:

```
71f08848c75f        appsody/java-microprofile:0.2                           "/appsody/appsody-co…"   5 minutes ago        Up 5 minutes        0.0.0.0:32828->7777/tcp, 0.0.0.0:32827->9080/tcp, 0.0.0.0:32826->9443/tcp     cw-appsodyjava2-70c82eb0-990e-11e9-8fb3-6f3e9cb122d4
```

And the url that is being opened in the browser is: http://localhost:32827/

**Comment by eharris369** [comment]
This url works: http://localhost:32827/health

**Comment by eharris369** [comment]
This url, http://localhost:32827/starter, gives:
```
Error 500: javax.servlet.ServletException: At least one provider or resource class should be specified for application class "dev.appsody.starter.StarterApplication
```

**Comment by makandre** [comment]
https://github.com/appsody/stacks/tree/master/incubator/java-microprofile

The README documents 4 endpoints that should work:

- Health endpoint: http://localhost:9080/health
- Metrics endpoint: http://localhost:9080/metrics (login as admin user with adminpwd password)
- OpenAPI endpoint: http://localhost:9080/openapi
- Swagger UI endpoint: http://localhost:9080/openapi/ui

`metrics` one require https but it doesn't work (there are some errors wrt to the SSL port which may be a separate bug); the other ones do work

But absent is `/` and there's no other "Hello World" route available (but have spoken to appsody developer and they agreed one probably should be added)

**Comment by makandre** [comment]
~@eharris369 It re-tested this today, and the java-microprofile stack might have been updated because now I would see the Open Liberty landing page at `/`~

![image](https://user-images.githubusercontent.com/17596240/60603190-3fe8aa80-9d83-11e9-94ea-d5f0d2fac59a.png)

~Does this address your concerns for this issue?~

Edit: never mind... sometimes it shows, sometimes it doesn't...

**Comment by makandre** [comment]
Found there's actually an appsody PR that aims to address this: https://github.com/appsody/stacks/pull/47

**Comment by makandre** [comment]
https://github.com/appsody/stacks/pull/47 is fixed so now there is a nice landing page at the root path

![image](https://user-images.githubusercontent.com/17596240/61225225-284be300-a6ee-11e9-9ad9-3540b4062a10.png)

I'm going to close this issue, feel free to re-open if you feel there are other things that need to be addressed regarding this.
