### ISSUE TITLE
Appsody projects on Eclipse show up empty

### ISSUE THREAD

**Issue by Jhschube** [kabanero-io/appsodyExtension#11]
Basically you can create an appsody project and it will run successfully. But when Eclipse tries to open up the project, its just an empty folder. So you can't really develop with this on Eclipse yet.

**Comment by makandre** [comment]
Hi @Jhschube, could you include some more information about your usage?

- Does it happen with node or java appsody projects?
- So the project appears empty after it is imported from the Codewind explorer view into the Eclipse workspace?
- Have you tried this in VSCode?
- Could you attach any logs in your `codewind-workspace/.logs/<projectName>-<projectID>/` folder?

**Comment by Jhschube** [comment]
1. Both of them
2. The project is not able to expand, so it appears empty but in the codewind-workspace dir on my computer it is populated.
![image](https://user-images.githubusercontent.com/36675747/60916578-c6f2c280-a25c-11e9-89cc-bd132cd72709.png)
3. Yes and it works. Only having this problem in Eclipse
4.
[appsody.log](https://github.com/kabanero-io/appsodyExtension/files/3374539/appsody.log)

**Comment by makandre** [comment]
@Jhschube Could you try right-click and refresh in the project explorer?

**Comment by Jhschube** [comment]
Wow I thought I did that. Well that solved that problem.

**Comment by makandre** [comment]
If this consistently happens, maybe it's worth a shot to open an issue on https://github.com/eclipse/codewind-eclipse

**Comment by Jhschube** [comment]
Sounds good
