### ISSUE TITLE
Investigate running apps without servers on codewind

### ISSUE THREAD

**Issue by sghung** [kabanero-io/appsodyExtension#16]
The nodejs and swift don't have a server, but codewind expects it. Need to see if codewind will be able to support an app that doesn't start as a server.

**Comment by sghung** [comment]
There is work to have improved detailed messages on the ID team to let the user know what the status would be (we wouldn't keep it as "Starting" and would give detailed messages to let the user know what is being pinged). 

TODO: review the messages and see if there's anything to clarify on the appsody case

**Comment by makandre** [comment]
Codewind pings now timeout after https://github.com/eclipse/codewind/pull/250 so such apps will now to go `stopped` state

Also documented this behaviour via https://github.com/eclipse/codewind-docs/pull/71
