### ISSUE TITLE
Dynamically generate the appsody templates and remove the old kabanero-io appsody templates

### ISSUE THREAD

**Issue by sghung** [kabanero-io/appsodyExtension#18]
We need to talk with the codewind folks to see how we can get around that requirement. Maybe we can have them implement another way that doesn't look at a codewind repo, but maybe allow us to generate the .appsody-config.yaml dynamically and put it into the workspace

**Comment by ebullient** [comment]
The appsody extension to codewind should perhaps wrap the CLI to discover/introspect configured repositories. The appsody repository already defines/references tgz files. If codewind can use the CLI to introspect an appsody repository, and then extract given the specified tgz, we're in good shape.

**Comment by sghung** [comment]
Part 1: ensure codewind can handle .tar.gz format and unzip it instead of just using github repo
Part 2: read their index from their github and discover the .tar.gz locations to use for the codewind templates
Part 3: if user set in the CLI, then possibly grab that index from the CLI

**Comment by tobespc** [comment]
I agree that the current method is clunky, I'll look at adding support for .tar.gz

**Comment by makandre** [comment]
Hi @tobespc, was planning to let @laven26 take a look at the .tar.gz support via #22.  He'll reach out to you.

**Comment by makandre** [comment]
This is available in https://github.com/eclipse/codewind-appsody-extension/releases/tag/0.3.0
