### ISSUE TITLE
Ensure the codewind, cli, and codewind vscode command palette is consistent

### ISSUE THREAD

**Issue by sghung** [kabanero-io/appsodyExtension#19]
- Appsody projects have a task.json with some appsody commands, but we need to ensure those are run in our docker container (where our appsody binary is hosted, not the appsody that may or may not be installed on the terminal)
- Appsody folks mentioned the task.json does not contain anything regarding repos, we should add that ourselves to allow users to add their own repos

**Comment by sghung** [comment]
On further discussion, codewind doesn't handle running things outside of the codewind command (e.g. manually building a docker container and starting the container for a codewind project), so making it consistent with the CLI is a stretch. Focus on the command palette consistently first.

**Comment by makandre** [comment]
Scope changed.  We relocated Codewind's appsody config to the workspace (#26) and provided instructions on how to configure local appsody to use the same configuration:

https://github.com/makandre/codewind-appsody-extension#optional-using-the-same-appsody-configuration-between-local-cli-and-codewind (will also be added to Codewind docs via https://github.com/eclipse/codewind-docs/issues/77)

This satisfies the scenario of someone using appsody CLI to add additional repos for Codewind to fetch templates from
