### ISSUE TITLE
Ensure for 3Q all available appsody stacks have a corresponding codewind template

### ISSUE THREAD

**Issue by sghung** [kabanero-io/appsodyExtension#21]
Ensure all the newly supported stacks can be used in codewind via templates.

**Comment by ebullient** [comment]
I would rather avoid creating any additional codewind templates for appsody (those intermediate repositories). A clearer statement would be: make sure that the appsody extension can surface all templates provided by an appsody repository, and that those templates can be used by codewind.

Specifically, #18

**Comment by makandre** [comment]
No longer relevant:  codebase moved to https://github.com/eclipse/codewind-appsody-extension and we are now consuming an `index.json` that is auto-generated by appsody
