### ISSUE TITLE
Read their index from their github and discover the .tar.gz locations to use for the codewind templates

### ISSUE THREAD

**Issue by sghung** [kabanero-io/appsodyExtension#23]
Part of https://github.com/kabanero-io/appsodyExtension/issues/18

We may need to gate the stacks we know we don't support (e.g. nodejs and swift), since we only want types that codewind supports.

**Comment by makandre** [comment]
Raised a request on appsody stacks https://github.com/appsody/stacks/issues/100

**Comment by makandre** [comment]
The design is change a bit after recent discussion.  Instead of returning template objects to Codewind, we return `index.json` urls.  #28 will need to be reworked and we also require https://github.com/eclipse/codewind/pull/114

**Comment by makandre** [comment]
This is available in https://github.com/eclipse/codewind-appsody-extension/releases/tag/0.3.0
