### ISSUE TITLE
Incremental/Local Development and Debug for java microprofile and spring

### ISSUE THREAD

**Issue by makandre** [kabanero-io/appsodyExtension#25]

**Comment by keithchong** [comment]
Currently as it stands, there is no incremental development support in an Appsody Java Microprofile project created via Codewind.

**Comment by makandre** [comment]
Could you elaborate?

**Comment by makandre** [comment]
This is available in https://github.com/eclipse/codewind-appsody-extension/releases/tag/0.3.0
